### PR TITLE
Fix https://github.com/jwiegley/github/issues/99

### PR DESCRIPTION
**Pull request by pharpend**

### CODE REVIEW

**Comment by hdgarrood** [comment]
This will fail for `base < 4.8`. There's no need to use CPP - just do what I described in #99.

**Comment by pharpend** [comment]
@hdgarrood Well, I did the CPP thing before I read your comment. The CPP thing works, I think. I don't understand your solution.

**Comment by pharpend** [comment]
The tests pass, by the way.

**Comment by hdgarrood** [comment]
Ohh, my bad - I guess the type declaration for whatever type `defaultTimeLocale` is must have been copied into `time`, not re-exported. :+1: for this then.

**Comment by pharpend** [comment]
@jwiegley 

When are you planning on publishing a new version on Hackage?

The reason I ask is, https://github.com/snowdriftcoop/snowdrift/pull/305 is dependent on you pushing a new version.

**Comment by jwiegley** [comment]
In a few minutes. :)

**Comment by jwiegley** [comment]
Just waiting on the latest Nix changes to build so that I can test it.

**Comment by pharpend** [comment]
Ah alright. Thank you!

**Comment by jwiegley** [comment]
@pharpend Uploaded to Hackage as 0.13.2

**Comment by pharpend** [comment]
Thank you, jwiegley!

**Pull request merged**
