### PR TITLE
Getting a little more detail in place

### PR DESCRIPTION
**Pull request by bitemyapp**
Things are in better/more understandable shape than I remember them being. My problem in the past was figuring out how to use it for the activity feed, still unclear if that's supported.

Most functions have an individual example and are fairly simple, so I'd say the biggest need going forward is a more complete example using auth. Other than that, things are in reasonably good shape I'd say :+1:

### CODE REVIEW

**Comment by jwiegley** [comment]
If I had my druthers, we'd auto-generate the APIs from a published spec, the way that `amazon-ka` does.

**Comment by bitemyapp** [comment]
@jwiegley Someone needs to make an API-Generator-Generator so we don't have to write one :smiling_imp:

**Comment by jwiegley** [comment]
A servant API generator would be dead sexy.  You listening, @dmjio? :)

**Comment by dmjio** [comment]
@jwiegley I hear ya :) I'm working on a servant-to-swagger project, but not a swagger-to-servant project. But it wouldn't be too difficult to go from swagger YAML to a servant type def.

**Pull request merged**
